import type { ChannelConfig, ChannelId } from './types';

export const CHANNEL_CONFIGS: Record<ChannelId, ChannelConfig> = {
  ch1: {
    id: 'ch1',
    name: 'Dopamine Loop',
    genre: 'Psychology & Behavior',
    voice: 'en-US-GuyNeural',
    voiceRate: '+15%',
    voicePitch: '+0Hz',
    bodyFont: "'Space Grotesk', sans-serif",
    accentFont: "'Anton', sans-serif",
    colors: {
      bgPrimary:  '#16121f',
      accent1:    '#d400ff',
      accent2:    '#00f0ff',
      text:       '#ffffff',
      textMuted:  'rgba(255,255,255,0.55)',
    },
    scriptTone:     'punchy, direct, mind-bending',
    beatTypes:      ['person', 'stat', 'none'],
    musicMood:      'upbeat electronic',
    sfxProfile:     'electronic',
    uploadSchedule: 'daily 18:00 UTC',
  },
  ch2: {
    id: 'ch2',
    name: 'FinanceFiction',
    genre: 'Finance & Business',
    voice: 'en-US-DavisNeural',
    voiceRate: '+10%',
    voicePitch: '-2Hz',
    bodyFont: "'Space Grotesk', sans-serif",
    accentFont: "'Anton', sans-serif",
    colors: {
      bgPrimary:  '#0a0e1a',
      accent1:    '#00ff88',
      accent2:    '#ff4444',
      text:       '#e8e8e8',
      textMuted:  'rgba(232,232,232,0.55)',
    },
    scriptTone:     'analytical, shocking, authoritative',
    beatTypes:      ['brand', 'stat', 'person'],
    musicMood:      'tense corporate',
    sfxProfile:     'corporate',
    uploadSchedule: 'daily 14:00 UTC',
  },
  ch3: {
    id: 'ch3',
    name: 'Redacted',
    genre: 'Conspiracy & Classified',
    voice: 'en-US-TonyNeural',
    voiceRate: '+5%',
    voicePitch: '-5Hz',
    bodyFont: "'Space Grotesk', sans-serif",
    accentFont: "'Anton', sans-serif",
    colors: {
      bgPrimary:  '#080808',
      accent1:    '#cc0000',
      accent2:    '#f0f0f0',
      text:       '#e0e0e0',
      textMuted:  'rgba(224,224,224,0.55)',
    },
    scriptTone:     'conspiratorial, terse, urgent',
    beatTypes:      ['person', 'place', 'none'],
    musicMood:      'dark ambient',
    sfxProfile:     'dark',
    uploadSchedule: 'daily 20:00 UTC',
  },
  ch4: {
    id: 'ch4',
    name: 'The Grey Matter',
    genre: 'Neuroscience',
    voice: 'en-GB-SoniaNeural',
    voiceRate: '+8%',
    voicePitch: '+0Hz',
    bodyFont: "'Space Grotesk', sans-serif",
    accentFont: "'Anton', sans-serif",
    colors: {
      bgPrimary:  '#12121e',
      accent1:    '#e94560',
      accent2:    '#4cc9f0',
      text:       '#f0f0f0',
      textMuted:  'rgba(240,240,240,0.55)',
    },
    scriptTone:     'scientific, vivid, revelatory',
    beatTypes:      ['anatomy', 'person', 'stat'],
    musicMood:      'calm cinematic',
    sfxProfile:     'soft',
    uploadSchedule: 'daily 16:00 UTC',
  },
  ch5: {
    id: 'ch5',
    name: 'The Quiet Record',
    genre: 'Hidden History',
    voice: 'en-GB-RyanNeural',
    voiceRate: '+3%',
    voicePitch: '+0Hz',
    bodyFont: "'Space Grotesk', sans-serif",
    accentFont: "'Anton', sans-serif",
    colors: {
      bgPrimary:  '#100d08',
      accent1:    '#c8a96e',
      accent2:    '#f5f0e8',
      text:       '#f5f0e8',
      textMuted:  'rgba(245,240,232,0.55)',
    },
    scriptTone:     'measured, evocative, archival',
    beatTypes:      ['person', 'place', 'none'],
    musicMood:      'documentary cinematic',
    sfxProfile:     'cinematic',
    uploadSchedule: 'daily 12:00 UTC',
  },
  ch6: {
    id: 'ch6',
    name: 'Red Space Facts',
    genre: 'Astronomy & Space',
    voice: 'en-US-AriaNeural',
    voiceRate: '+12%',
    voicePitch: '+0Hz',
    bodyFont: "'Space Grotesk', sans-serif",
    accentFont: "'Anton', sans-serif",
    colors: {
      bgPrimary:  '#050010',
      accent1:    '#ff4500',
      accent2:    '#a0c4ff',
      text:       '#e8f0ff',
      textMuted:  'rgba(232,240,255,0.55)',
    },
    scriptTone:     'awe-inspiring, precise, cosmic',
    beatTypes:      ['celestial', 'stat', 'distance'],
    musicMood:      'space ambient',
    sfxProfile:     'space',
    uploadSchedule: 'daily 10:00 UTC',
  },
};
