import { ChannelConfig } from './types';

export const CHANNEL_CONFIGS: Record<string, ChannelConfig> = {
  ch1: {
    id: 'ch1',
    name: 'Dopamine Loop',
    genre: 'Psychology & Behaviour',
    accentColor: '#d400ff',
    bgColor: '#16121f',
    fontHeading: 'Anton',
    fontBody: 'Space Grotesk',
    voice: 'en-US-AvaNeural',
    voiceRate: '+8%',
    voicePitch: 'default',
    scriptTone:
      'Second-person, fast sentences. The hook must make the viewer question their own behaviour. The mechanism explains the brain chemistry or psychology mechanism — specific neurotransmitter names, study citations. The twist is a "you do this right now without knowing it" reveal.',
    musicMood: 'synthwave / retro electronic',
    sfxProfile: 'kenney_retro',
    colors: {
      bgPrimary: '#16121f',
      accent1: '#d400ff',
      accent2: '#00f0ff',
      text: '#ffffff',
      textMuted: 'rgba(255,255,255,0.6)',
    },
  },
  ch2: {
    id: 'ch2',
    name: 'FinanceFiction',
    genre: 'Finance & Business',
    accentColor: '#00ff88',
    bgColor: '#0a0e1a',
    fontHeading: 'JetBrains Mono',
    fontBody: 'Space Grotesk',
    voice: 'en-US-DavisNeural',
    voiceRate: 'default',
    voicePitch: 'default',
    scriptTone:
      'Tell the story of a single number. Name the specific company, CEO, or event. Build cinematic tension around a real financial consequence. The mechanism explains the exact sequence of cause and effect. The twist is a counter-intuitive implication that reframes the number.',
    musicMood: 'tense cinematic / thriller',
    sfxProfile: 'cinematic_tension',
    colors: {
      bgPrimary: '#0a0e1a',
      accent1: '#00ff88',
      accent2: '#ff4444',
      text: '#ffffff',
      textMuted: 'rgba(255,255,255,0.6)',
    },
  },
  ch3: {
    id: 'ch3',
    name: 'Redacted',
    genre: 'Classified History & Conspiracy',
    accentColor: '#cc0000',
    bgColor: '#080808',
    fontHeading: 'Special Elite',
    fontBody: 'Special Elite',
    voice: 'en-US-BrianNeural',
    voiceRate: '-5%',
    voicePitch: '-2st',
    scriptTone:
      'Clipped, declassified-file cadence. Name real people, real dates, real operations. Withhold the key fact until the twist. Every sentence earns the next. The outro implies there is more still classified.',
    musicMood: 'dark ambient / suspense drone',
    sfxProfile: 'cinematic_suspense',
    colors: {
      bgPrimary: '#080808',
      accent1: '#cc0000',
      accent2: '#1a1305',
      text: '#e8e0cc',
      textMuted: 'rgba(232,224,204,0.6)',
    },
  },
  ch4: {
    id: 'ch4',
    name: 'The Grey Matter',
    genre: 'Neuroscience',
    accentColor: '#0097a7',
    bgColor: '#0d1117',
    fontHeading: 'Space Grotesk',
    fontBody: 'Space Grotesk',
    voice: 'en-US-AndrewNeural',
    voiceRate: 'default',
    voicePitch: 'default',
    scriptTone:
      'Calm, analogy-led. Name the specific brain region, specific neurotransmitter, specific study. Explain the mechanism with one physical analogy. The outro poses the open scientific question the field has not yet answered.',
    musicMood: 'ambient electronic / calm science',
    sfxProfile: 'soft_electronic',
    colors: {
      bgPrimary: '#0d1117',
      accent1: '#0097a7',
      accent2: '#5e35b1',
      text: '#ffffff',
      textMuted: 'rgba(255,255,255,0.6)',
    },
  },
  ch5: {
    id: 'ch5',
    name: 'The Quiet Record',
    genre: 'History',
    accentColor: '#c8a96e',
    bgColor: '#1a1410',
    fontHeading: 'Playfair Display',
    fontBody: 'Space Grotesk',
    voice: 'en-GB-SoniaNeural',
    voiceRate: '-8%',
    voicePitch: '-1st',
    scriptTone:
      'Reflective, past-tense documentary voice. Specific date, specific location, specific person. The twist is a quiet historical irony that recontextualises the event. The outro lands on a resonant connection to the present.',
    musicMood: 'melancholic piano / orchestral / documentary',
    sfxProfile: 'orchestral_subtle',
    colors: {
      bgPrimary: '#1a1410',
      accent1: '#c8a96e',
      accent2: '#8b6340',
      text: '#f0e6d3',
      textMuted: 'rgba(240,230,211,0.6)',
    },
  },
  ch6: {
    id: 'ch6',
    name: 'Red Space Facts',
    genre: 'Space & Astronomy',
    accentColor: '#ff4500',
    bgColor: '#050010',
    fontHeading: 'Orbitron',
    fontBody: 'Space Grotesk',
    voice: 'en-US-AriaNeural',
    voiceRate: 'default',
    voicePitch: 'default',
    scriptTone:
      'Awe first, precision second. Name the specific body, mission, or phenomenon. Every beat includes one mind-expanding specific number with real context (not "millions" — say "4.6 billion"). Facts checked against research sources.',
    musicMood: 'cosmic space-synth / orchestral',
    sfxProfile: 'cosmic_ambient',
    colors: {
      bgPrimary: '#050010',
      accent1: '#ff4500',
      accent2: '#00d4ff',
      text: '#ffffff',
      textMuted: 'rgba(255,255,255,0.6)',
    },
  },
};

export const ALL_CHANNEL_IDS = ['ch1', 'ch2', 'ch3', 'ch4', 'ch5', 'ch6'] as const;
